---
- name: Install Apache (apache2) on Ubuntu
  tags: apache, ubuntu
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Start and enable Apache service on Ubuntu
  tags: apache, ubuntu, apache2
  service:
    name: apache2
    state: started
    enabled: true
